"""num pages

Revision ID: 33b67fab8e5f
Revises: e8f856b32d6
Create Date: 2016-09-22 15:06:54.636247

"""

# revision identifiers, used by Alembic.
revision = '33b67fab8e5f'
down_revision = 'e8f856b32d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Site', sa.Column('num_pages', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Site', 'num_pages')
    ### end Alembic commands ###
