"""Site model

Revision ID: 4afb5ac769eb
Revises: None
Create Date: 2016-09-22 12:41:41.161390

"""

# revision identifiers, used by Alembic.
revision = '4afb5ac769eb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Site',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('key', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Site')
    ### end Alembic commands ###
