"""Page

Revision ID: 564276188447
Revises: 33b67fab8e5f
Create Date: 2016-09-22 15:23:00.934281

"""

# revision identifiers, used by Alembic.
revision = '564276188447'
down_revision = '33b67fab8e5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Site', sa.Column('last_relay_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Site', 'last_relay_at')
    ### end Alembic commands ###
