"""Site.data

Revision ID: d09e370a6bb
Revises: 564276188447
Create Date: 2016-09-23 16:22:34.045495

"""

# revision identifiers, used by Alembic.
revision = 'd09e370a6bb'
down_revision = '564276188447'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Site', sa.Column('data', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Site', 'data')
    ### end Alembic commands ###
