"""page model

Revision ID: e8f856b32d6
Revises: 5623a7c88d59
Create Date: 2016-09-22 14:54:11.828684

"""

# revision identifiers, used by Alembic.
revision = 'e8f856b32d6'
down_revision = '5623a7c88d59'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Page', sa.Column('data', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    op.drop_column('Page', 'links')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Page', sa.Column('links', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('Page', 'data')
    ### end Alembic commands ###
